### PR TITLE
Switched to removeChild method, works cross-browser

### PR DESCRIPTION
**Pull request by joefhall**

### CODE REVIEW

**Comment by joefhall** [comment]
[BUG: [POD Point Ltd CMS] ERROR: TypeError: Object doesn't support property or method 'remove'](https://trello.com/c/otgXqaYV/127-bug-pod-point-ltd-cms-error-typeerror-object-doesn-t-support-property-or-method-remove)

**Comment by joefhall** [comment]
Thanks! Should be in there now in latest commit

**Comment by edcs** [comment]
I feel like I shouldn't be seeing this 🤔 (sorry, couldn't think of another way of letting you know).

**Comment by mikefrancis** [comment]
@edcs Hai! It's because it's a public repo and you're watching it I think.

**Pull request merged**
